### PR TITLE
add some change

### PR DESCRIPTION
**Pull request by riccardonar**
I'm not a ruby programmer, but i do some changes:
- html in issues/_form (for compatibility with redmine 3.2.1, i think..)
- html in settings to standards with other settings pages
- manage auth with redmine permissions (add some permessions in mega calendar)
- add italian translation
- css calendar more responsive

There are some things to do, but I do not know if I am able:
- modify holidays to manage also hours
- the user's color could be managed with hook
- add permission to magage your or all holidays
- create issue directly from calendar, it can be a link to new issue with date and hour

### CODE REVIEW

**Comment by berti92** [comment]
Hi,

thank you for your work.

I'll check your merge request in the next time. Many things you've done I would implement in Version 2.
Please be patient.

**Comment by riccardonar** [comment]
Hi,
i have work to plugin:
- issue time and user color now are custom fields
- holidays manage also time

but so i loose the datepicker in time issues and colorpicker in user color..
The idea is to create a plugin for custom filed **color** and **time** but.. i need an help..

**Comment by lhadjadj** [comment]
Hi all, is it possible to have only the demands of the project and not all projects (including those not visible) ? Thanks

**Comment by berti92** [comment]
Hi,

I'm sorry I don't understand your question.
You mean a filter in the calendar?

VG Berti

**Comment by lhadjadj** [comment]
Hi thanks for your answer, 
actually The button "all my issue" get all issues from all projets even il The project is not public. A filter or just to get all the issues from the main project wiil ne fine.

Sorry for my english with french auto-correction (thanks Apple, lol). I upgrade fullcalendar on version 2.9.1, it is ok, i find the calendar controller and the request for issues but i don't understand how it works. 

So, if it is not clear, i Will post tommorow with google translate.

Envoyé de mon iPad

**Comment by berti92** [comment]
Because of long inactivty and over the time merge conflicts, this PR is closed. Sorry.

**Pull request closed without merging**
